version: '3.7'




services:
  redis:
    image: redis/redis-stack:latest
    ports: 
      - 10001:6379
  client:
    build: ./client
    ports: 
      - 3000:3000
  server:
    build: ./server
    ports: 
      - 5000:5000


