version: '3.7'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 10001:6379
  
  
  # mongodb:
    # image: mongo:5.0
    # ports:
    #   - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=english
    #   - MONGO_INITDB_ROOT_PASSWORD=root